#!/usr/bin/env bash
export TAGFILE='./src/git-tag.dhall'

eval $(dhall-to-bash --declare NAME <<< "let tag = ${TAGFILE} in tag.tag")
eval $(dhall-to-bash --declare MESSAGE <<< "let tag = ${TAGFILE} in tag.message")

git tag -a ${NAME} -m "${MESSAGE}"
git push origin ${NAME}
